🎨feat : TodoList 내용 추가 기능 및 레이아웃
ydw1996/David_Review pull request #4
Opened 2023-01-29 17:44 UTC by ydw1996

## ✅ PR 체크리스트
-  코드 스타일 가이드 규칙을 준수했어요.

## PR 타입
설명하실 변경 사항은 어떤 종류인가요?

- [ ] 버그 수정
- [ ] 기능 추가
- [x] 코드 스타일 업데이트
- [ ] 기타

## 이슈 번호 : #4 

## 해당 PR이 프로젝트에 큰 영향이 있나요?

- [ ] Yes
- [x] No

## 작업 내용
- React 컴포넌트를 활용한 TodoList 내용 추가 기능 및 레이아웃 틀 작업 

### 추가 설명

2023-01-30 01:13 UTC, raymondanythings requested changes

2023-01-30 01:13 UTC, raymondanythings commented on src/App.js
> +          <input value ={inputValue}type="text" onChange={(event)=>setInputValue(event.target.value)}/>
p1: 이벤트 핸들러는 함수로 설정하는게 좋을 것 같습니다

2023-01-30 01:13 UTC, raymondanythings commented on src/components/TodoBoard.js
> +function TodoBoard(props){
p1: 컴포넌트 props는 구조분해 할당하는 것이 좋을 것 같습니다

2023-01-30 01:13 UTC, raymondanythings commented on src/components/TodoItem.js
> +function TodoItem(props) {
p1: 컴포넌트 props는 구조분해 할당하는 것이 좋을 것 같습니다

2023-01-30 01:23 UTC, HerrineKim approved these changes

2023-01-30 01:23 UTC, HerrineKim commented on src/App.js
> +  const [inputValue,setInputValue] = useState('')
p5: 콤마(,)와 다음 변수 사이는 띄어쓰기를 하는 원칙을 적용하시면 가독성이 높아질 것 같아요

2023-01-30 04:17 UTC, SoJeongMun approved these changes

2023-01-30 12:00 UTC, cheonkyu commented on src/components/TodoBoard.js
> +function TodoBoard(props){
@raymondanythings 

동의합니다. 구조분해 할당을 했을 때, 좋은점 세 가지 나열 해봅니다.

```js
function TodoBoard({ todoList }) { ... }
```
1. 불필요한 반복된 키워드 제거 ( props.~.~ )
2. 키워드별 검색이 용이
3. 해당 함수(컴포넌트)가 무슨 필드, 값인지 유추 가능

2023-01-30 15:08 UTC, raymondanythings commented on src/components/TodoBoard.js
> +function TodoBoard(props){
굿정리입니다👍

2023-01-30 19:36 UTC, ydw1996 commented on src/App.js
> +  const [inputValue,setInputValue] = useState('')
좋은 의견 감사합니다. 반영해 볼게요 :)

2023-01-30 19:36 UTC, ydw1996 commented on src/App.js
> +          <input value ={inputValue}type="text" onChange={(event)=>setInputValue(event.target.value)}/>
네 이벤트 핸들러 함수로 코드 작업해 보겠습니다

2023-01-30 19:36 UTC, ydw1996 commented on src/components/TodoBoard.js
> +function TodoBoard(props){
네 구조 분해 코드 작성 진행해볼게요

2023-01-30 19:36 UTC, ydw1996 commented on src/components/TodoItem.js
> +function TodoItem(props) {
여기도 구조 분해 코드 작성 진행해볼게요

2023-01-30 19:46 UTC, ydw1996 commented on src/components/TodoBoard.js
> +function TodoBoard(props){
커밋 하려고 하는데 커밋이 안되서 아침에 여쭤보겠습니다.

2023-01-31 13:28 UTC, raymondanythings approved these changes

2023-02-01 01:42 UTC, cheonkyu commented on src/App.js
> +  const addItem =() => {
다음 번엔 useCallback이나 다른 훅을 사용하는 법은 숙달해보셨으면 합니다.

2023-02-01 01:42 UTC, cheonkyu approved these changes

2023-02-01 01:56 UTC, cheonkyu approved these changes

2023-02-02 19:30 UTC, merged